feat: add `bohemia.studio`
c0reme/bohemia pull request #1
Opened 2022-12-14 14:07 UTC by prontozz

- [x] add to population script 0475075f3d69c9dc4837eeb8b937a11eba8cd5cd, cfd386c5286af6b58025f6daee87f51aededc4b8
- [x] add to tests  e636da0dc55c202295d695a08c0e4365b5a808e5

2022-12-14 14:51 UTC, c0reme requested changes
Not bad, please could you make sure these are changed then request a review afterwards.

2022-12-14 14:51 UTC, c0reme commented on tests/postgres.test.js
> +      expect(res.rowCount).toBe(6);
More tests on the columns are needed here, something on the lines of
```js
res.rows.forEach((row) => {
  expect(row).toHaveProperty('studioName');
  // ....
});
```

2022-12-20 11:24 UTC, c0reme commented on scripts/CreationScript.sql
> +    email varchar(255) not null
Updated locally with 8fa40113ebd7202f7a53a2d39bedcc7c608357f0

2022-12-20 18:23 UTC, prontozz commented on tests/postgres.test.js
> +      expect(res.rowCount).toBe(6);
Something along the lines of this?

`res.rows.forEach((row) => {
        expect(row).toHaveProperty('studioName');
        expect(row).toHaveProperty('description');
        expect(row).toHaveProperty('studioHead');
        expect(row).toHaveProperty('addressFK');
        expect(row).toHaveProperty('phone');
        expect(row).toHaveProperty('alternatePhone');
        expect(row).toHaveProperty('email');
      });`

2022-12-20 19:09 UTC, merged